name: Feature Request
description: Suggest an idea for this project. Fields are repeated because you need to write them both in English and Spanish / Los campos se repiten porque debes escribirlos en inglés y en español.
title: "[Feature Request]: "
labels: "enhancement"
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/White-Mask/DoozieDo/blob/main/CONTRIBUTING.md) for this project.
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/White-Mask/DoozieDo/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
- type: textarea
  attributes:
    label: Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like in a clear and concise manner.
  validations:
    required: true

- type: textarea
  attributes:
    label: Descripción
    description: Por favor, añade una descripción clara y concisa del problema que estás tratando de resolver con esta solicitud de funcionalidad.
  validations:
    required: True
- type: textarea
  attributes:
    label: Solución Propuesta
    description: Describe la solución que te gustaría de manera clara y concisa.
  validations:
    required: True